#!/bin/sh

# https://github.com/mozilla/grcov

cd $(dirname $0)/..

export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
export RUSTDOCFLAGS="-Cpanic=abort"

cargo build
cargo test
[ "$cover_lcov" != "" ] && {
	grcov . -s ./src --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/debug/lcov.info
	genhtml -o ./target/debug/coverage/ --show-details --highlight --ignore-errors source --legend ./target/debug/lcov.info
} || {
	grcov . -s ./src --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage
}

cd - >/dev/null 2>&1
